<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/

/**
 * Return the webservice description for an entity type.
 *
 * The standard description generated by the registered entity handler is kept
 * unchanged. For administrators, globally disabled fields are added separately
 * under the "inactiveFields" key to preserve backwards compatibility for API
 * clients which process the standard "fields" array. Non-admin users do not
 * receive this additional key.
 *
 * @param string $elementType Webservice entity name, for example Contacts.
 * @param Users  $user        Authenticated CRM user.
 *
 * @return array<string, mixed> Entity description; inactiveFields is included
 *                              only for administrators.
 *
 * @throws WebServiceException If the user may not access the entity type.
 */
function vtws_describe($elementType, $user) {

	global $log, $adb;
	$webserviceObject = VtigerWebserviceObject::fromName($adb, $elementType);
	$handlerPath = $webserviceObject->getHandlerPath();
	$handlerClass = $webserviceObject->getHandlerClass();

	require_once $handlerPath;

	$handler = new $handlerClass($webserviceObject, $user, $adb, $log);
	$meta = $handler->getMeta();

	$types = vtws_listtypes(null, $user);
	if (!in_array($elementType, $types['types'])) {
		throw new WebServiceException(
			WebServiceErrorCode::$ACCESSDENIED,
			"Permission to perform the operation is denied"
		);
	}

	$entity = $handler->describe($elementType);
	if (is_admin($user)) {
		$entity['inactiveFields'] = vtws_describeInactiveFields($elementType, $meta);
	}

	VTWS_PreserveGlobal::flush();
	return $entity;
}

/**
 * Return fields which exist in vtiger_field but are globally disabled.
 *
 * A field is considered inactive when vtiger_field.presence equals 1. No
 * generatedtype filter is applied, therefore both standard fields and custom
 * fields (named cf_*) are included.
 *
 * Webservice-only entity types do not necessarily have an associated tab ID.
 * In that case an empty array is returned.
 *
 * @param string     $elementType Webservice entity name.
 * @param EntityMeta $meta        Metadata object returned by the entity handler.
 *
 * @return array<int, array<string, mixed>> Inactive field descriptions.
 */
function vtws_describeInactiveFields($elementType, $meta) {

	global $adb;

	$tabId = null;
	$tabName = $elementType;

	if (is_object($meta) && is_callable(array($meta, 'getEffectiveTabId'))) {
		$tabId = $meta->getEffectiveTabId();
	} 
	elseif (is_object($meta) && is_callable(array($meta, 'getTabId'))) {
		$tabId = $meta->getTabId();
	}

	if (is_object($meta) && is_callable(array($meta, 'getTabName'))) {
		$tabName = $meta->getTabName();
	}

	if (empty($tabId) && function_exists('getTabid')) {
		$tabId = getTabid($tabName);
	}

	// Webservice-only entity types do not necessarily have vtiger_field entries.
	if (empty($tabId)) {
		return array();
	}

	$sql = 'SELECT fieldid, fieldname, fieldlabel, columnname, tablename, '
		. 'uitype, typeofdata, displaytype, generatedtype, block, sequence '
		. 'FROM vtiger_field '
		. 'WHERE tabid = ? AND presence = 1 '
		. 'ORDER BY block, sequence, fieldid';
	$result = $adb->pquery($sql, array($tabId));

	if (!$result) {
		return array();
	}

	$inactiveFields = array();
	$rowCount = $adb->num_rows($result);

	for ($index = 0; $index < $rowCount; ++$index) {
		$row = $adb->fetchByAssoc($result, $index);
		$generatedType = (int) $row['generatedtype'];

		$inactiveFields[] = array(
			'name' => $row['fieldname'],
			'label' => getTranslatedString($row['fieldlabel'], $tabName),
			'columnName' => $row['columnname'],
			'tableName' => $row['tablename'],
			'uiType' => (int) $row['uitype'],
			'typeOfData' => $row['typeofdata'],
			'displayType' => (int) $row['displaytype'],
			'generatedType' => $generatedType,
			'custom' => ($generatedType === 2),
			'fieldId' => (int) $row['fieldid'],
			'blockId' => (int) $row['block'],
			'sequence' => (int) $row['sequence'],
			'presence' => 1
		);
	}

	return $inactiveFields;
}

?>
