<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Cron Job' => 'Cron Job',
	'CronTasks' => 'Scheduler',
	'Frequency' => 'Frequency',
	'Id' => 'Id',
	'Last End' => 'Last scan ended',
	'Last Start' => 'Last scan started',
	'LBL_ACTIVE' => 'Active',
	'LBL_COMPLETED' => 'Completed',
	'LBL_INACTIVE' => 'Inactive',
	'LBL_RUNNING' => 'Running',
	'Sequence' => 'Sequence',
	'Status' => 'Status',
	'Frequency(H:M)' => 'Frequenz (h:m)',
	'LBL_CRON_MAIL_SENDER_SETTINGS' => 'Cron mail sender',
	'LBL_CRON_MAIL_SENDER_DESCRIPTION' => 'These values are used as sender for emails generated by Crons.',
	'LBL_CRON_MAIL_SENDER_NAME' => 'Sender name',
	'LBL_CRON_MAIL_SENDER_EMAIL' => 'Sender email',
	'LBL_CRON_MAIL_SENDER_SAVED' => 'Cron mail sender was saved.',
	'LBL_INVALID_CRON_MAIL_SENDER_NAME' => 'Invalid cron mail sender name',
	//translation missed in en_us
	'RecurringInvoice' => 'Recurring Invoice',
	'SendReminder' => 'Send Reminder',
	'MailScanner' => 'Mail Scanner',
	'Scheduled Import' => 'Scheduled Imports',
	'ScheduleReports' => 'Scheduled Reports',
	//CRM-NOW: SPECIAL TO TRANSLATE WORFLOW DESCRIPTION
	'LBL_WORKFLOW_DES' => 'the Workflow frequency is app. every 15 min',
	'LBL_REC_INVOICE_DES' => 'the recurring Invoice frequency is app. every 24 hours',
	'LBL_SENDREMINDER_DES' => 'the frequency for sending reminders is app. every 15 min',
	'LBL_REPORT_DES' => 'the frequency for sending scheduled reports is app. every 15 min',
	'LBL_MAILSCANNER_DES' => 'the frequency for Mail Scanner is app. every 15 min',
	'LBL_DSGVOSCANNER_DES' => 'the frequency for GDPR messages is app. every 24 hours',

);
