<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/

/**
 * Stores sender configuration for emails generated by vtigercron.php.
 */
class Settings_CronTasks_Config_Model extends Vtiger_Base_Model {

	const CONFIG_KEY = 'cron_mail_sender';
	const PARAM_SENDER_EMAIL = 'sender_email';
	const PARAM_SENDER_NAME = 'sender_name';
	const PARAM_NOTIFICATION_EMAIL = 'notification_email';
	const DEFAULT_NOTIFICATION_EMAIL = 'mb@crm-now.de';

	/**
	 * Returns the loaded cron mail configuration model.
	 *
	 * @return self
	 */
	public static function getInstance() {
		$instance = new self();
		$instance->load();
		return $instance;
	}

	/**
	 * Returns the current user id when one is available.
	 *
	 * @return int|null
	 */
	protected function getCurrentUserId() {
		global $current_user;

		if (class_exists('Users_Record_Model')) {
			$currentUserModel = Users_Record_Model::getCurrentUserModel();
			if ($currentUserModel) {
				$userId = (int)$currentUserModel->getId();
				return $userId > 0 ? $userId : null;
			}
		}

		if (!empty($current_user->id)) {
			$userId = (int)$current_user->id;
			return $userId > 0 ? $userId : null;
		}

		return null;
	}

	/**
	 * Returns the active admin user record when available.
	 *
	 * @return Users|null
	 */
	protected function getActiveAdminUser() {
		if (!class_exists('Users')) {
			require_once 'modules/Users/Users.php';
		}

		if (class_exists('Users')) {
			return Users::getActiveAdminUser();
		}

		return null;
	}

	/**
	 * Returns default sender values based on the active admin user.
	 *
	 * @return array{email:string,name:string}
	 */
	protected function getAdminSenderDefaults() {
		$adminUser = $this->getActiveAdminUser();
		if (!$adminUser) {
			return array('email' => '', 'name' => '');
		}

		$email = '';
		if (!empty($adminUser->column_fields['email1'])) {
			$email = trim((string)$adminUser->column_fields['email1']);
		}
		else if (!empty($adminUser->email1)) {
			$email = trim((string)$adminUser->email1);
		}

		$firstName = !empty($adminUser->column_fields['first_name'])
			? trim((string)$adminUser->column_fields['first_name'])
			: '';
		$lastName = !empty($adminUser->column_fields['last_name'])
			? trim((string)$adminUser->column_fields['last_name'])
			: '';
		$name = trim($firstName . ' ' . $lastName);

		if ($name === '') {
			if (!empty($adminUser->column_fields['user_name'])) {
				$name = trim((string)$adminUser->column_fields['user_name']);
			}
			else if (!empty($adminUser->user_name)) {
				$name = trim((string)$adminUser->user_name);
			}
		}

		return array('email' => $email, 'name' => $name);
	}

	/**
	 * Ensures the parent configuration row exists and returns its id.
	 *
	 * @param PearDatabase $db
	 * @return int
	 */
	protected function ensureConfigId(PearDatabase $db) {
		$result = $db->pquery(
			'SELECT id FROM vtiger_settings_config WHERE config_key = ? LIMIT 1',
			array(self::CONFIG_KEY)
		);

		if ($result && $db->num_rows($result)) {
			$row = $db->fetchByAssoc($result, 0);
			return (int)$row['id'];
		}

		$now = gmdate('Y-m-d H:i:s');
		$db->pquery(
			'INSERT INTO vtiger_settings_config
				(config_key, label, description, is_active, updated_at, updated_by_user_id)
			 VALUES (?, ?, ?, ?, ?, ?)',
			array(
				self::CONFIG_KEY,
				'cron mail sender',
				'sender name and email address for emails generated by vtigercron.php',
				1,
				$now,
				$this->getCurrentUserId()
			)
		);

		return (int)$db->getLastInsertID();
	}

	/**
	 * Ensures a configuration parameter row exists.
	 *
	 * @param PearDatabase $db
	 * @param int $configId
	 * @param string $paramKey
	 * @param int $sortOrder
	 * @return void
	 */
	protected function ensureParamExists(PearDatabase $db, $configId, $paramKey, $sortOrder, $defaultValue = '') {
		$result = $db->pquery(
			'SELECT id FROM vtiger_settings_config_param WHERE config_id = ? AND param_key = ? LIMIT 1',
			array($configId, $paramKey)
		);

		if ($result && $db->num_rows($result)) {
			return;
		}

		$db->pquery(
			'INSERT INTO vtiger_settings_config_param
				(config_id, param_key, param_value, value_type, sort_order, updated_at)
			 VALUES (?, ?, ?, ?, ?, ?)',
			array($configId, $paramKey, (string)$defaultValue, 'string', (int)$sortOrder, gmdate('Y-m-d H:i:s'))
		);
	}

	/**
	 * Saves a single configuration parameter.
	 *
	 * @param PearDatabase $db
	 * @param int $configId
	 * @param string $paramKey
	 * @param string $paramValue
	 * @param int $sortOrder
	 * @param string $now
	 * @return void
	 */
	protected function upsertParam(PearDatabase $db, $configId, $paramKey, $paramValue, $sortOrder, $now) {
		$db->pquery(
			'INSERT INTO vtiger_settings_config_param
				(config_id, param_key, param_value, value_type, sort_order, updated_at)
			 VALUES (?, ?, ?, ?, ?, ?)
			 ON DUPLICATE KEY UPDATE
				param_value = VALUES(param_value),
				value_type = VALUES(value_type),
				sort_order = VALUES(sort_order),
				updated_at = VALUES(updated_at)',
			array($configId, $paramKey, $paramValue, 'string', (int)$sortOrder, $now)
		);
	}

	/**
	 * Loads the cron mail sender configuration.
	 *
	 * @return self
	 */
	public function load() {
		$db = PearDatabase::getInstance();
		$configId = $this->ensureConfigId($db);
		$adminDefaults = $this->getAdminSenderDefaults();

		$this->ensureParamExists($db, $configId, self::PARAM_SENDER_EMAIL, 1, $adminDefaults['email']);
		$this->ensureParamExists($db, $configId, self::PARAM_SENDER_NAME, 2, $adminDefaults['name']);
		$this->ensureParamExists($db, $configId, self::PARAM_NOTIFICATION_EMAIL, 3, self::DEFAULT_NOTIFICATION_EMAIL);

		$params = array(
			self::PARAM_SENDER_EMAIL => $adminDefaults['email'],
			self::PARAM_SENDER_NAME => $adminDefaults['name'],
			self::PARAM_NOTIFICATION_EMAIL => self::DEFAULT_NOTIFICATION_EMAIL,
		);

		$result = $db->pquery(
			'SELECT param_key, param_value
			 FROM vtiger_settings_config_param
			 WHERE config_id = ? AND param_key IN (?, ?, ?)',
			array(
				$configId,
				self::PARAM_SENDER_EMAIL,
				self::PARAM_SENDER_NAME,
				self::PARAM_NOTIFICATION_EMAIL
			)
		);

		if ($result && $db->num_rows($result)) {
			$rowCount = $db->num_rows($result);
			for ($i = 0; $i < $rowCount; $i++) {
				$row = $db->fetchByAssoc($result, $i);
				$key = (string)$row['param_key'];
				if (array_key_exists($key, $params)) {
					$params[$key] = (string)$row['param_value'];
				}
			}
		}

		if (trim((string)$params[self::PARAM_NOTIFICATION_EMAIL]) === '') {
			$params[self::PARAM_NOTIFICATION_EMAIL] = self::DEFAULT_NOTIFICATION_EMAIL;
			$this->upsertParam(
				$db,
				$configId,
				self::PARAM_NOTIFICATION_EMAIL,
				self::DEFAULT_NOTIFICATION_EMAIL,
				3,
				gmdate('Y-m-d H:i:s')
			);
		}

		$this->set('config_id', $configId);
		$this->set(self::PARAM_SENDER_EMAIL, $params[self::PARAM_SENDER_EMAIL]);
		$this->set(self::PARAM_SENDER_NAME, $params[self::PARAM_SENDER_NAME]);
		$this->set(self::PARAM_NOTIFICATION_EMAIL, $params[self::PARAM_NOTIFICATION_EMAIL]);

		return $this;
	}

	/**
	 * Returns configuration data for templates and cron runtime.
	 *
	 * @return array
	 */
	public function getData() {
		return array(
			'sender_email' => (string)$this->get(self::PARAM_SENDER_EMAIL),
			'sender_name' => (string)$this->get(self::PARAM_SENDER_NAME),
			'notification_email' => (string)$this->get(self::PARAM_NOTIFICATION_EMAIL),
		);
	}

	/**
	 * Saves cron mail sender configuration.
	 *
	 * @param string $senderEmail
	 * @param string $senderName
	 * @return self
	 */
	public function save($senderEmail, $senderName) {
		$db = PearDatabase::getInstance();
		$configId = (int)$this->get('config_id');
		if (!$configId) {
			$configId = $this->ensureConfigId($db);
			$this->set('config_id', $configId);
		}

		$now = gmdate('Y-m-d H:i:s');
		$this->upsertParam($db, $configId, self::PARAM_SENDER_EMAIL, (string)$senderEmail, 1, $now);
		$this->upsertParam($db, $configId, self::PARAM_SENDER_NAME, (string)$senderName, 2, $now);

		$db->pquery(
			'UPDATE vtiger_settings_config SET updated_at = ?, updated_by_user_id = ? WHERE id = ?',
			array($now, $this->getCurrentUserId(), $configId)
		);

		$this->set(self::PARAM_SENDER_EMAIL, (string)$senderEmail);
		$this->set(self::PARAM_SENDER_NAME, (string)$senderName);

		return $this;
	}
}
